### ISSUE TITLE
R U SURE THIS PLUGIN IS USELESS?

### ISSUE THREAD

**Issue by PepbookPvP** [jose-vm/UHCPluginPM#2]
Hmm...I saw the introduction and it said 'Useless until PM has Nether'.You see, Genisys, ImagicalMine, These two kernel based on PM but they have Nether and it works perfect. And these kernels also have more features do PM hasn't. I think you could update this plugin:-)

**Comment by corytortoise** [comment]
I agree, I think this plugin would be super popular with things like:
A timer with grace period
Commands to start a match
Etc.

**Comment by jose-vm** [comment]
oops im watching this until now lol
